//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelDBContainer : DbContext
    {
        public ModelDBContainer()
            : base("name=ModelDBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kitap> KitapSet { get; set; }
        public virtual DbSet<Yazar> YazarSet { get; set; }
        public virtual DbSet<YayinEvi> YayinEviSet { get; set; }
        public virtual DbSet<Kategori> KategoriSet { get; set; }
        public virtual DbSet<Kullanici> KullaniciSet { get; set; }
        public virtual DbSet<Admin> AdminSet { get; set; }
        public virtual DbSet<OkunanKitap> OkunanKitaplar { get; set; }
    }
}
