//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkunanKitap
    {
        public int Id { get; set; }
        public System.DateTime AlısTarih { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
    
        public virtual Kitap Kitap { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
